version: "3"

services:
  redis:
    image: redis:7.0.5-alpine
    restart: always
    volumes:
      - redis:/data
    networks:
      - jasmin
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      retries: 3
      timeout: 5s

  rabbit-mq:
    image: rabbitmq:3.11.3-alpine
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - jasmin
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 3

  celery-worker:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.celery
    image: jasmin:celery-worker
    restart: always
    networks:
      - jasmin
    depends_on:
      - rabbit-mq
    environment:
      REDIS_HOST: ${REDIS_CLIENT_HOST:-redis}
      REDIS_PORT: ${REDIS_CLIENT_PORT:-6379}
      AMQP_BROKER_HOST: ${AMQP_BROKER_HOST:-rabbit-mq}
      AMQP_BROKER_PORT: ${AMQP_BROKER_PORT:-5672}

  celery-beat:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.celery
    image: jasmin:celery-beat
    restart: always
    networks:
      - jasmin
    depends_on:
      - rabbit-mq
    environment:
      REDIS_HOST: ${REDIS_CLIENT_HOST:-redis}
      REDIS_PORT: ${REDIS_CLIENT_PORT:-6379}
      AMQP_BROKER_HOST: ${AMQP_BROKER_HOST:-rabbit-mq}
      AMQP_BROKER_PORT: ${AMQP_BROKER_PORT:-5672}
    healthcheck:
      test: ["CMD", "celery", "-A", "jasmin.protocols.rest.tasks", "inspect", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    image: mher/flower
    restart: always
    networks:
      - jasmin
    depends_on:
      - celery-worker
    ports:
      - '${FORWARD_FLOWER_PORT:-5555}:5555'
    environment:
      CELERY_BROKER: ${CELERY_BROKER_URL:-amqp://guest:guest@rabbit-mq:5672/}

  jasmin:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.restapi.alpine
    image: jasmin:restapi
    restart: always
    ports:
      - '${FORWARD_JASMIN_SMPP_PORT:-2775}:2775'
      - '${FORWARD_JASMIN_CLI_PORT:-8990}:8990'
      - '${FORWARD_JASMIN_HTTP_PORT:-1401}:1401'
    volumes:
      - jasmin_config:/etc/jasmin
      - jasmin_store:/etc/jasmin/store
      - jasmin_logs:/var/log/jasmin
    tmpfs:
      - /tmp
    networks:
      - jasmin
    depends_on:
      redis:
        condition: service_healthy
      rabbit-mq:
        condition: service_healthy
      celery-worker:
        condition: service_healthy
      celery-beat:
        condition: service_healthy
    environment:
      REDIS_CLIENT_HOST: ${REDIS_CLIENT_HOST:-redis}
      REDIS_CLIENT_PORT: ${REDIS_CLIENT_PORT:-6379}
      AMQP_BROKER_HOST: ${AMQP_BROKER_HOST:-rabbit-mq}
      AMQP_BROKER_PORT: ${AMQP_BROKER_PORT:-5672}
      ENABLE_PUBLISH_SUBMIT_SM_RESP: ${ENABLE_PUBLISH_SUBMIT_SM_RESP:-1}
      RESTAPI_MODE: ${RESTAPI_MODE:-0}

  jasmin-restapi:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.restapi
    image: jasmin:restapi
    restart: always
    ports:
      - '${FORWARD_JASMIN_RESTAPI_PORT:-8080}:8080'
    volumes:
      - restapi_logs:/var/log/jasmin
    tmpfs:
      - /tmp
    networks:
      - jasmin
    depends_on:
      - jasmin
      - celery-worker
    environment:
      REDIS_CLIENT_HOST: ${REDIS_CLIENT_HOST:-redis}
      REDIS_CLIENT_PORT: ${REDIS_CLIENT_PORT:-6379}
      AMQP_BROKER_HOST: ${AMQP_BROKER_HOST:-rabbit-mq}
      AMQP_BROKER_PORT: ${AMQP_BROKER_PORT:-5672}
      RESTAPI_MODE: ${RESTAPI_MODE:-1}
      RESTAPI_OLD_HTTP_HOST: ${RESTAPI_OLD_HTTP_HOST:-jasmin}

networks:
  jasmin:
    driver: bridge
volumes:
  jasmin_config: {}
  jasmin_store: {}
  jasmin_logs: {}
  restapi_logs: {}
  rabbitmq: {}
  redis: {}
